### ISSUE TITLE
gulp-jade

### ISSUE THREAD

**Issue by LEI** [CREEATION/laravel-elixir-jade#16]
Hi,

FYI the gulp-jade dependency is missing in the package.json, throwing an error if you are not setting the jadephp option to true.

https://github.com/CREEATION/laravel-elixir-jade/blob/master/index.js#L37

```
Error: Cannot find module 'gulp-jade'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Function.<anonymous> (/home/vagrant/node_modules/laravel-elixir-jade/index.js:37:57)
    at Function.<anonymous> (/home/vagrant/node_modules/laravel-elixir/index.js:40:18)
    at /home/vagrant/gulpfile.js:156:10
    at Elixir (/home/vagrant/node_modules/laravel-elixir/index.js:16:5)
    at Object.<anonymous> (/home/vagrant/gulpfile.js:76:1)
    at Module._compile (module.js:398:26)
```

**Comment by lazytyper** [comment]
Thanks, it should be fixed now.
